config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :rooms, only: %i[index show new create] do
    resources :bookings, only: %i[new create]
    resources :reviews, only: :create
  end
  resources :bookings, except: %i[new create]
  namespace :owner do
    resources :bookings, only: %i[index update] # included update in the resources so owner can accept / reject
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates_presence_of :date, :number_of_people, :status
  validates :number_of_people, numericality: { only_integer: true }
  enum :status, { requested: 0, accepted: 1, rejected: 2 }

  validate :different_users
  validate :compare_capacity

  private

  def different_users
    if user == room.user
      errors.add(:user, "can't be the same as the room's user")
    end
  end

  def compare_capacity
    if number_of_people > room.capacity
      errors.add(:number_of_people, "can't go over capacity")
    end
  end


end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :room
  belongs_to :user

  validates :content, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :users, through: :bookings
  has_many :reviews
  has_one_attached :photo

  validates_presence_of :name, :address, :story, :description, :capacity, :price
  validates :price, :capacity, numericality: { only_integer: true }

  include PgSearch::Model
  # multisearchable against: [:name, :description]

  pg_search_scope :search_by_attributes,
    against: [ :name, :description, :story, :address ],
    using: {
      tsearch: { prefix: true }
    }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  has_many :rooms
  has_many :bookings_as_owner, through: :rooms, source: :bookings

  validates :username, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  include Pundit::Authorization

  # Pundit: allow-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = policy_scope(Booking)
  end

  def create
    @room = Room.find(params[:room_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.room = @room
    authorize(@booking)
    if @booking.save
      redirect_to bookings_path
    else
      render "rooms/show", status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    # we must authorize the booking using pundit after its created. we'll redirect to the bookings page after its deleted.
    authorize(@booking)
    @booking.destroy
    redirect_to bookings_path
  end

  private
  # strong params -> white listing the info coming from the form
  def booking_params
    params.require(:booking).permit(:date, :number_of_people)
  end
end

app/controllers/owner/bookings_controller.rb
class Owner::BookingsController < ApplicationController
  def index
    # @owner_rooms = Room.where(user: current_user)
    # @rooms_bookings = Booking.all.each_with_object([]) do |booking, list|
    #   list << booking if booking.room.user == current_user # @owner_rooms.include?(booking.room)
    # end
    @rooms_bookings = policy_scope([:owner, Booking]).sort
  end

  def update

    @booking = Booking.find(params[:id])
    # need to authorize only within the owner scope / owner space
    authorize([:owner, @booking])
    @booking.status = params[:booking][:status]
    if @booking.save
      redirect_to owner_bookings_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = policy_scope(Review)
  end

  def create
    @room = Room.find(params[:room_id])
    @review = Review.new(review_params)
    @review.user = current_user
    @review.room = @room
    authorize(@review)

    respond_to do |format|
      if @review.save
        format.html { redirect_to room_path(@room) }
        format.json do
          render json: {
            review_html: render_to_string(partial: "reviews/review", formats: :html, locals: { review: @review }),
            form_html: render_to_string(partial: "reviews/new", formats: :html, locals: { room: @review.room, review: Review.new }),
        }.to_json
      end
      else
        format.html { render "rooms/show", status: :unprocessable_entity }
        format.json do
          render json: {
            form_html: render_to_string(partial: "reviews/new", formats: :html, locals: { room: @review.room, review: @review }),
        }.to_json
        end
      end
    end
    # raise
    # if @review.save
    #   redirect_to room_path(@room)
    # else
    #   render "rooms/show", status: :unprocessable_entity
    # end
  end

  private

  # strong params -> white listing the info coming from the form
  def review_params
    params.require(:review).permit(:content)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = policy_scope(Room)
    @owned_rooms = @rooms.where(user: current_user)
    @not_owned_rooms = @rooms.where.not(user: current_user)
    @markers = @not_owned_rooms.geocoded.map do |room|
      {
        lat: room.latitude,
        lng: room.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {room:})
      }
    end
    # if params[:query].present?
    #   sql_subquery = <<~SQL
    #     rooms.name ILIKE :query
    #     OR rooms.description ILIKE :query
    #     OR rooms.story ILIKE :query
    #     OR users.username ILIKE :query
    #   SQL
    #   @not_owned_rooms = @not_owned_rooms.joins(:user).where(sql_subquery, query: "%#{params[:query]}%")
    # end
    if params[:query].present?
      @not_owned_rooms = Room.search_by_attributes(params[:query]).where.not(user: current_user)
    end
  end

  # def index
  #   @movies = Movie.all
  #   if params[:query].present?
  #     @movies = @movies.where(title: params[:query])
  #   end
  # end

  def show
    @room = Room.find(params[:id])
    @booking = Booking.new
    @review = Review.new
    authorize @room
    # authorize @booking
  end

  def new
    @room = Room.new
    authorize @room
  end

  def create
    @room = Room.new(room_params)
    @room.user = current_user
    authorize(@room)

    if @room.save
      redirect_to room_path(@room)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  # strong params -> white listing the info coming from the form
  def room_params
    params.require(:room).permit(:name, :address, :capacity, :description, :story, :price, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="page-frame-content">
  <div class="page-frame-header">
    <%= render 'shared/navbar'%>
  </div>
  <div class="page-frame-body">
    <h1 class="book py-3" >Your bookings</h1>
    <div class="container">
      <%@bookings.each do |booking|%>
        <div class="card-booking-container">
          <div class="card-booking">
            <% if booking.room.photo.key  %>
              <%= cl_image_tag booking.room.photo.key, height: 120, crop: :fill %>
            <% else %>
              <%= image_tag 'https://res.cloudinary.com/dfv1szuzs/image/upload/v1684227581/development/fkzdohnna0ay3tsdb9iyykwrpknq.jpg', alt: "text", style: 'width: 400px' %>
            <% end %>
            <div class="card-booking-infos">
              <h2><%=link_to booking.room.name, room_path(booking.room)%></h2>
              <p>Booked by <strong>you</strong> on <strong><%=booking.date%></strong> for <%=booking.number_of_people%> people</p>
            </div>
            <div class="card-booking-status">
              <p>Status: <strong><%=booking.status%></strong></p>
              <%= link_to "Cancel", booking_path(booking), data: { turbo_method: :delete, turbo_confirm: "Cancel this booking?" } %>
            </div>
          </div>
        </div>
      <%end%>
    </div>
  </div>
  <div class="page-frame-footer">
    <%= link_to "view rooms", rooms_path%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Breakstuff</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <%# <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <div class="footer">
      <%# <div class="footer-links">
        <a href="#"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
      </div>
      <div class="navbar footer-copyright">
        This footer is the temp footer
      </div> %>
    </div>
  </body>
</html>

app/views/owner/bookings/index.html.erb
<div class="page-frame-content">
  <div class="page-frame-header">
    <%= render 'shared/navbar'%>
  </div>
  <div class="page-frame-body">
    <h1 class="book py-3">
      <%= "You have #{@rooms_bookings.count} reservation#{@rooms_bookings.count > 1 || @rooms_bookings.count ==0 ? "s": ""}" %>
    </h1>
    <div class="container">
      <% @rooms_bookings.each do |booking|%>
        <div class="card-booking">
          <% if booking.room.photo.key  %>
            <%= cl_image_tag booking.room.photo.key, height: 120, crop: :fill %>
          <% else %>
            <img src='https://res.cloudinary.com/dfv1szuzs/image/upload/v1684227581/development/fkzdohnna0ay3tsdb9iyykwrpknq.jpg' style='width: 400'>
          <% end %>
          <div class="card-right">
            <div class="card-booking-infos">
              <h2><%=link_to booking.room.name, room_path(booking.room)%></h2>
              <p>Booked by <strong><%=booking.user.username%></strong> on <strong><%=booking.date%></strong> for <%=booking.number_of_people%> people</p>
              <p>Status: <strong><%=booking.status%></strong></p>
            </div>
            <div class="booking-status-card">
              <%=simple_form_for booking, url: owner_booking_path(booking) do |f| %> <!-- the url is specified on the FORM, and its owner_booking (no s) -->
                <%=f.input :status, as: :hidden, input_html: {value: "accepted"} %>
                <%=f.submit 'accept', class: 'btn btn-outline-primary custom'%>
              <%end%>
              <%=simple_form_for booking, url: owner_booking_path(booking) do |f| %>
                <%=f.input :status, as: :hidden, input_html: {value: "rejected"}%>
                <%=f.submit 'reject', class: 'btn btn-outline-warning custom'%>
              <%end%>
            </div>
          </div>
        </div>
        <!-- card-booking -->
      <%end%>
    </div>
  </div>
</div>
<div class="page-frame-footer">
  <%= link_to "view rooms", rooms_path%>
</div>

app/views/pages/home.html.erb
<div class="page-frame-content">
  <div class="page-frame-header">
    <%= render "shared/navbar" %>
  </div>
  <div class="page-frame-body">
    <div class="mw-100">
      <video class="rage-video" autoplay muted loop id="myVideo">
        <source src="/rage-video.mp4" type="video/mp4">
      </video>
      <div class="container banner-info">
        <h2>Smash your pain away!</h2>
        <p>Relieve stress. Break stuff.</p>
        <%= link_to("Browse Rage Rooms", rooms_path, {class: "btn btn-dark"}) %>
      </div>
    </div>
  </div>
</div>

app/views/reviews/_new.html.erb
<%# partial %>
<%= simple_form_for([room, review],
                          data: {insert_in_list_target: "form",
                          action: "submit->insert-in-list#send"
                          }) do |f|
                         %>
<%= f.input :content %>
<%= f.button :submit %>
<% end %>

app/views/reviews/_review.html.erb
<%# name of the partial should be what is taken from html %>
<div class="reviews-card">
  <div class="reviews-user"><%=review.user.username%>:</div>
  <div class="reviews-content">"<%=review.content%>"</div>
</div>

app/views/rooms/_info_window.html.erb
<h4><%= room.name %></h4>
<p><%= room.address %></p>

app/views/rooms/index.html.erb
<div class="page-frame-content">
  <div class="page-frame-header">
    <%= render "shared/navbar" %>
  </div>
  <div class="page-frame-body">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-sm-8 my-3">
          <%= form_with url: rooms_path, method: :get, class: "d-flex" do %>
            <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Search for a room"
        %>
            <%= submit_tag "Search", name: "", class: "btn btn-dark" %>
          <% end %>
        </div>
      </div>
      <h1 class="book py-3"><strong>BOOK THE ROOM YOU WANT TO SMASH</strong></h1>
      <div class="container mt-3 i ">
        <div class="cards">
          <% @not_owned_rooms.each do |room| %>
            <div class="card-pick mx-auto">
              <h2><%= room.name%></h2>
              <% if room.photo.key  %>
                <%= cl_image_tag room.photo.key, height: 300, width: 400, crop: :fill %>
              <% else %>
                <%= cl_image_tag "ue8b275gg03z61ydvkz6why3roed", height: 300, width: 400, crop: :fill %>
              <% end %>
              <div class="card-pick-info">
                <h3>Location: <%= room.address.gsub(/\d{3}-\d{4}/, "") %></h3>
                <h3> <%= number_to_currency(room.price, unit: "￥", strip_insignificant_zeros: true) %> </h3>
                <h6>  <%= room.description %></h6>
                <h6> Owned by <em><%= room.user.username%></em></h6>
                <%= link_to "", room_path(room), class:"card-pick-link" %>
              </div>
            </div>
          <% end %>
        </div>
        <%# this div is for the map %>
        <div
          class='mt-3'
          style="width: 100%; height: 300px;"
          data-controller="map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>
    <h1 class="book py-3"> <strong>MY ROOMS</strong></h1>
    <div class="container">
      <div class="container mt-3">
        <div class="cards">
          <% @owned_rooms.each do |room| %>
            <div class="card-pick mx-auto">
              <h2><%= room.name %></h2>
              <% if room.photo.key %>
                <%= cl_image_tag room.photo.key, height: 300, width: 400, crop: :fill %>
              <% else %>
                <%= cl_image_tag "ue8b275gg03z61ydvkz6why3roed", height: 300, width: 400, crop: :fill %>
              <% end %>
              <div class="card-pick-info">
                <h3>Location: <%= room.address.gsub(/\d{3}-\d{4}/, "") %></h3>
                <h3> ¥ <%= room.price %> </h3>
                <h6>  <%= room.description %></h6>
                <h6> Owned by <em><%= room.user.username%></em></h6>
                <%= link_to "", room_path(room), class:"card-pick-link" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="page-frame-footer">
  </div>
</div>

app/views/rooms/new.html.erb
<%= render "shared/navbar" %>
<div class="container mt-3 d-flex justify-content-center">
  <div class="card col-sm-8 col-md-6">
    <div class="row p-3 m-2">
      <%= simple_form_for @room do |f|%>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :story %>
        <%= f.input :description %>
        <%= f.input :capacity %>
        <%= f.input :price %>
        <%= f.input :photo, as: :file %>
        <%= f.submit 'add new room', class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>
<%=link_to "view rooms", rooms_path%>

app/views/rooms/show.html.erb
<div class="page-frame-content">
  <div class="page-frame-header">
    <%= render 'shared/navbar'%>
  </div>
  <div class="page-frame-body">
    <div class="room-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @room.photo.key ? cl_image_path(@room.photo.key, crop: :pad) : cl_image_path("ue8b275gg03z61ydvkz6why3roed", crop: :pad) %>);">
      <h1><strong><%=@room.name%>!</strong></h1>
      <div class="room-banner-info">
        <h3 class="mt-2"><%=@room.description%></h3>
        <h3 class="mt-3"><strong>Address: <%=@room.address%></strong></h3>
        <h3><strong>Capacity: <%= @room.capacity %></strong></h3>
        <h3><strong>Price: <%=  number_to_currency(@room.price, unit: "￥", strip_insignificant_zeros: true) %> / day</strong></h3>
        <h4 class="mt-5"><%=@room.story%></h4>
      </div>
    </div>
    <!-- -->
    <div data-controller="insert-in-list">
      <div class="review-header">
        <h2>See what others say</h2>
      </div>
      <div class="reviews-list">
        <div data-insert-in-list-target="items">
          <% @room.reviews.each do |review|%>
            <%=render "reviews/review", review: review%>
          <%end%>
        </div>
      </div>
      <!-- -->
      <% if current_user != @room.user %>
        <div class="bookings-container">
          <div class="bookings-card">
            <h2 class="text-center mt-3">Book this room?</h2>
            <div class="container m-3 d-flex justify-content-center">
              <div class="card" style="min-width: 360px;">
                <div class="row p-2 m-3">
                  <%= simple_form_for [@room, @booking] do |f|%>
                    <%= f.input :date, html5: true, input_html: { min: Date.today} %>
                    <%= f.input :number_of_people %>
                    <%= f.submit 'book this room', class: "btn btn-primary" %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <div class="bookings-card">
            <% if @room.bookings.any? { |b| b.user == current_user} %>
              <h2 class="text-center mt-3">Leave a review</h2>
              <div class="container m-3 d-flex justify-content-center">
                <div class="card" style="min-width: 360px; min-height: 260px">
                  <div class="row p-2 m-3">
                    <%= render "reviews/new", room: @room, review: @review %>
                  </div>
                </div>
              </div>
            <% else%>
              <h2 class="text-center mt-3">Make a booking to leave a review!</h2>
            <% end %>
          </div>
        </div>
      </div>
    <%end%>
  </div>
  <div class="page-frame-footer">
  </div>
</div>
</div>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <div class="container-fluid">
    <div class="hammer-header text-light">
      <h1 class="nav-bar-header"><%= link_to "Breakstuff", "/" %></h1>
      <i class="icon fa-solid fa-hammer"></i>
    </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if current_user.present? %>
          <li class="nav-item active">
            <div class="tags text-light"><%= link_to "Browse Rage Rooms",  "/rooms", class: "underlined" %></div>
          </li>
          <li class="nav-item active">
            <div class="tags text-light"><%= link_to "Bookings",  "/bookings", class: "underlined" %></div>
          </li>
          <li class="nav-item active">
            <div class="tags text-light"><%= link_to "Hosted Bookings",  "/owner/bookings", class: "underlined" %></div>
          </li>
        <% end %>
        <li class="nav-item">
          <a class="tags underlined" href="#" text-light>About</a>
        </li>
        <li class="nav-item">
          <a class="tags underlined" href="#" text-light>Contact us</a>
        </li>
        <li class="nav-item dropdown">
          <i class="fa-solid fa-bars menu" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/ssaunier"></i>
          <div class="dropdown-menu dropdown-menu-end menu-opacity" aria-labelledby="navbarDropdown" style="none">
            <p><%= current_user.username if current_user.present?%></p>
            <a class="dropdown-item" href="#"><%= link_to "Add a room", "/rooms/new", class: "item-dark" %></a>
            <a class="dropdown-item" href="#"><%= link_to "Login", "/users/sign_in", class: "item-dark" %></a>
            <a class="dropdown-item" data-turbo-method="delete" href="#"><%= link_to "Log Out", "/users/sign_out", class: "item-dark", data: {turbo_method: :delete} %></a>
          </div>
        </li>
        <!--li class="nav-item"-->
        <!--/li-->
      </ul>
    </div>
  </div>
</div>